// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfr0lRifgNpKakRzvJ1BJaR8xweoKg8Ds',
    appId: '1:109669668763:web:35e2b7de70892bd82cb33e',
    messagingSenderId: '109669668763',
    projectId: 'foodie-7407d',
    authDomain: 'foodie-7407d.firebaseapp.com',
    storageBucket: 'foodie-7407d.appspot.com',
    measurementId: 'G-0HX4VEQ0CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdff9ahw8Nnx3i2hkBzP1f9Z1SWo2XJuU',
    appId: '1:109669668763:android:913b883071edbd622cb33e',
    messagingSenderId: '109669668763',
    projectId: 'foodie-7407d',
    storageBucket: 'foodie-7407d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy1hahlBFxv1-4GVCRuCAXbzfO_mbEEqM',
    appId: '1:109669668763:ios:6f161ab529d92de42cb33e',
    messagingSenderId: '109669668763',
    projectId: 'foodie-7407d',
    storageBucket: 'foodie-7407d.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy1hahlBFxv1-4GVCRuCAXbzfO_mbEEqM',
    appId: '1:109669668763:ios:6f161ab529d92de42cb33e',
    messagingSenderId: '109669668763',
    projectId: 'foodie-7407d',
    storageBucket: 'foodie-7407d.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfr0lRifgNpKakRzvJ1BJaR8xweoKg8Ds',
    appId: '1:109669668763:web:50486ceb25c3854f2cb33e',
    messagingSenderId: '109669668763',
    projectId: 'foodie-7407d',
    authDomain: 'foodie-7407d.firebaseapp.com',
    storageBucket: 'foodie-7407d.appspot.com',
    measurementId: 'G-QWL3QXQVKV',
  );
}
